### ISSUE TITLE
Convert default variable usage to values

### ISSUE THREAD

**Issue by RcRonco** [RcRonco/role2md#8]
Convert default variable usage to values.
example of the problem:
```yaml
---
var1: "Hello world!"
var2: {{ var1 }}
```
default value with be ```var1``` instead of ```"Hello World"```
